name: Dog API CD

run-name: ${{ github.actor }} is running the Dog API CD

on:
  push:
    # paths:
    #   - "./deployments/environments/dev/dog-api/service.yaml"

jobs:

  deploy:

    runs-on: ubuntu-latest
    environment: dev

    steps:

      - name: Checkout code from repository
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.2
        with:
          workload_identity_provider: 'projects/798819781972/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider'
          service_account: learndevopsfromscratch@devopsfromscratch.iam.gserviceaccount.com
    
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2.1.0'

      - name: Deploy
        run: |
          gcloud run deploy --source=./service.yaml
        working-directory: deployments/environments/dev/dog-api
